[package]
name = "goap-ai"
version = "0.2.0"
edition = "2021"

[dependencies]
colored = "2.2.0"
pathfinding = "4.13.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"

[lib]
name = "goap_ai"
path = "src/lib.rs"

[[bin]]
name = "goap"
path = "src/main.rs"
