max_depth: 18
solution: Fast
state:
  properties:
    energy: 150
goals:
  - weight: 1
    property: "energy"
    target: 50
    kind: GreaterThanOrEqualTo
    scale: 0.01
actions:
  - label: "energy_up"
    duration: 2
    deltas:
      energy: 10
  - label: "energy_down"
    duration: 2
    deltas:
      energy: -10
