max_depth: 10
algorithm: Hybrid
solution: Fast
state:
  energy: 50
  health: 20
  num_apples: 2
  num_uncooked_meat: 0
  num_cooked_meat: 0
goals:
  health:
    target: 100
    kind: GreaterThanOrEqualTo
    weight: 4
  energy:
    target: 100
    kind: GreaterThanOrEqualTo
    weight: 1
actions:
  - label: gather
    duration: 1
    deltas:
      energy: -5
      num_apples: 5
  - label: hunt
    duration: 20
    deltas:
      energy: -10
      num_uncooked_meat: 3
  - label: cook
    duration: 2
    deltas:
      energy: -5
      num_uncooked_meat: -1
      num_cooked_meat: 1
  - label: eat_apple
    duration: 1
    deltas:
      energy: 5
      health: 5
      num_apples: -1
  - label: eat_cooked_meat
    duration: 1
    deltas:
      energy: 20
      health: 30
      num_cooked_meat: -1
  - label: rest
    duration: 5
    deltas:
      energy: 10
  - label: wait
    duration: 1
    deltas:
      energy: -1
